# Generated by Django 4.2.3 on 2023-08-30 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255, null=True)),
                ('tuoi', models.IntegerField(null=True)),
                ('chuc_vu', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_phong', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='ten_phong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhanvien_set', to='app.phongban'),
        ),
    ]
